server:
  port: 8080
spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka-cluster-8761/eureka,http://eureka-cluster-8762/eureka
    initial-instance-info-replication-interval-seconds: 0
    instance-info-replication-interval-seconds: 1
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
logging:
  level:
    root: debug
